site_name: FastAPI Users
site_description: Ready-to-use and customizable users management for FastAPI

theme:
  name: 'material'
  custom_dir: docs-overrides
  palette:
    - scheme: default
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/weather-night
          name: Switch to light mode
  icon:
    logo: material/account-supervisor
  favicon: 'favicon.png'
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate

repo_name: frankie567/fastapi-users
repo_url: https://github.com/fastapi-users/fastapi-users
edit_uri: ""

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - tables
  - def_list

plugins:
  - search
  - mike

extra:
  version:
    provider: mike

nav:
  - About: index.md
  - installation.md
  - Configuration:
    - configuration/overview.md
    - User model and databases:
      - configuration/databases/sqlalchemy.md
      - configuration/databases/beanie.md
    - Authentication backends:
      - Introduction: configuration/authentication/index.md
      - Transports:
        - configuration/authentication/transports/cookie.md
        - configuration/authentication/transports/bearer.md
      - Strategies:
        - configuration/authentication/strategies/database.md
        - configuration/authentication/strategies/jwt.md
        - configuration/authentication/strategies/redis.md
      - configuration/authentication/backend.md
    - configuration/user-manager.md
    - configuration/schemas.md
    - Routers:
      - Introduction: configuration/routers/index.md
      - configuration/routers/auth.md
      - configuration/routers/register.md
      - configuration/routers/verify.md
      - configuration/routers/reset.md
      - configuration/routers/users.md
    - configuration/full-example.md
    - configuration/oauth.md
    - configuration/password-hash.md
  - Usage:
    - usage/flow.md
    - usage/routes.md
    - usage/current-user.md
  - Cookbook:
    - cookbook/create-user-programmatically.md
  - Migration:
    - migration/08_to_1x.md
    - migration/1x_to_2x.md
    - migration/2x_to_3x.md
    - migration/3x_to_4x.md
    - migration/4x_to_5x.md
    - migration/6x_to_7x.md
    - migration/7x_to_8x.md
    - migration/8x_to_9x.md
    - migration/9x_to_10x.md
