site_name: FastAPI Users
site_description: Ready-to-use and customizable users management for FastAPI

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/lightbulb
          name: Switch to dark mode
    - scheme: slate
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
  icon:
    logo: material/account-supervisor
  favicon: 'favicon.png'

repo_name: frankie567/fastapi-users
repo_url: https://github.com/fastapi-users/fastapi-users
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

nav:
  - About: index.md
  - installation.md
  - Configuration:
    - configuration/model.md
    - Databases:
      - configuration/databases/sqlalchemy.md
      - configuration/databases/mongodb.md
      - configuration/databases/tortoise.md
      - configuration/databases/ormar.md
    - Authentication:
      - Introduction: configuration/authentication/index.md
      - configuration/authentication/jwt.md
      - configuration/authentication/cookie.md
    - Routers:
      - Introduction: configuration/routers/index.md
      - configuration/routers/auth.md
      - configuration/routers/register.md
      - configuration/routers/reset.md
      - configuration/routers/users.md
      - configuration/routers/verify.md
    - configuration/password-validation.md
    - configuration/full-example.md
    - configuration/oauth.md
  - Usage:
    - usage/flow.md
    - usage/routes.md
    - usage/current-user.md
    - usage/helpers.md
  - Migration:
    - migration/08_to_1x.md
    - migration/1x_to_2x.md
    - migration/2x_to_3x.md
    - migration/3x_to_4x.md
    - migration/4x_to_5x.md
